# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen

language: julia
julia:
  - 1.3 # Earliest supported version
  - 1.6 # LTS
  - 1   # Stable
  - nightly

jobs:
  include:
    - stage: docs
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
